language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


  #before_script:
  # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "aaronwb"
  - git config user.email "zmtzwb@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${Travis_Token}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - master
env:
  global:
    - GH_REF: github.com/AaronW-BE/blog.git
